theme: jekyll-theme-minimal
title: Charlie Katerba
description: A website in progress that will eventually host some pet projects,
resume, cv, etc.

github_username:  ckaterba
twitter_username: CKaterba


# Build settings
lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

