theme : jekyll-theme-minimal
title : TBD
author: 
  name: Charles Katerba
  email: charles.katerba@gmail.com
  github: ckaterba

description: A website in progress that will eventually host some pet projects,
resume, cv, etc.

production_url : https://ckaterba.github.io

markdown: kramdown

BASE_PATH : https://ckaterba.github.io

# Build settings
# lsi: false
# safe: true
# source: # what goes here 
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge

